grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 3
    refit: roc_auc_ovr_weighted
    scoring: [f1_weighted, roc_auc_ovr_weighted, balanced_accuracy, neg_log_loss]

model_selection:
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      random_state: 2023
      max_depth: None
    search_param_grid:            
      n_estimators: [800]
      min_samples_split: [2, 6]
      min_samples_leaf: [1, 3]
      criterion: ['gini','log_loss']
      max_depth: [4,8,12,16,20, 24]
      max_features: [sqrt, log2]
      class_weight: [balanced, balanced_subsample]
      ccp_alpha: [0.0, 0.02, 0.04]
      

  module_2:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: auto
      weights: distance
    search_param_grid: 
      n_neighbors: [3, 6, 9]
      

